defaults: &dotnet
  docker:
    - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      environment:
        VERSION_PREFIX: "2.2"
  working_directory: ~/app

version: 2
jobs:
  build:
    <<: *dotnet
    steps:
      - checkout
      - run:
          name: Pack
          command: |
           export VERSION="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"
           dotnet pack -c Release -o ../../artifacts src/Xunit.Fixture.Mvc /p:PackageVersion=$VERSION /p:Version=$VERSION  /p:AssemblyVersion=$VERSION
      - persist_to_workspace:
          root: ~/app
          paths: .

  publish:
    <<: *dotnet
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Push NuGet packages
          command: dotnet nuget push artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          context: nuget-push
          filters:
            branches:
              only: master